### ISSUE TITLE
Can't run gulp - Cannot find module  './docs/_assets/customizer.js' on release v1.1.0

### ISSUE THREAD

**Issue by Roaders** [google/material-design-lite#4134]
Hi

I can't build the app and run the demos. Each time I try to build I get errors about no such file localizer.

I have tried several different version including 1.0.0 and 1.5.0 but I still get the problem.

I can'r run any of the samples in the src folder or see any of the demos.

**Comment by Roaders** [comment]
A bit more detail on this issue.
When I run "gulp all && gulp serve" I get the error:

```
[06:58:47] Starting 'styles:gen'...
[06:58:47] 'styles:gen' errored after 634 μs
[06:58:47] Error: Cannot find module './docs/_assets/customizer.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Gulp.<anonymous> (C:/dev/Web/materialDesignLite/gulpfile.babel.js:777:30)
    at module.exports (C:\dev\Web\materialDesignLite\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\dev\Web\materialDesignLite\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\dev\Web\materialDesignLite\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at C:\dev\Web\materialDesignLite\node_modules\gulp\node_modules\orchestrator\index.js:279:18
    at finish (C:\dev\Web\materialDesignLite\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
[06:58:47] 'all' errored after 6.12 s
[06:58:47] Error in plugin 'run-sequence'
Message:
    An error occured in task 'styles:gen'.
```

**Comment by surma** [comment]
Seems like you are trying to run `gulp all` on our npm package. That won’t work as it doesn’t include all the assets for the website etc.

Please clone the repository and try again on the `mdl-1.1` branch. `master` is very much in flux right now as we are working towards MDL v2.

**Comment by Roaders** [comment]
Thanks, it worked on `mdl-1.1`
