### ISSUE TITLE
MDL Stepper Polyfill

### ISSUE THREAD

**Issue by ahlechandre** [google/material-design-lite#4116]
As discussed at  #1748 issue, the stepper is a component that is present in the [Material Design specification](https://www.google.com/design/spec/components/steppers.html) and MDL has not support yet.

While the Material Design Lite team works in other parts of the library, i decided to create my own component.

This is the [MDL Stepper component](https://ahlechandre.github.io/mdl-stepper) and i would like to share with other developers.

Obviously, this is my interpretation of the spec and it does not reflect what the Material Design team would consider ‘correct’ but i tried to preserve as much of specified details.

You can consider this as a polyfill to be used while the MDL do not include that. Maybe it can be useful and help other people to build their web apps.

Be free to help develop this project too. Here's the first [issue](https://github.com/ahlechandre/mdl-stepper/issues/1).

Sorry for the off-topic but I think it can be constructive.

**Comment by tleunen** [comment]
You have an error, so the demos don't work :/
```
Uncaught TypeError: stepElements.forEach is not a function
```

**Comment by ahlechandre** [comment]
@tleunen Now i tested all the demos and worked well. You could specify where's the error?

**Comment by tleunen** [comment]
On this page: http://ahlechandre.github.io/mdl-stepper/component/index.html
`stepElements` is a NodeList, not an array. You have to convert it before using it (using `[].slice.call(stepElements).forEach(...)` for example)

**Comment by ahlechandre** [comment]
@tleunen All demo worked on my tests using chrome 49.0.2623.47. But i'll turn off the page, make new tests and then active again. Thank you for reporting.

**Comment by ahlechandre** [comment]
@tleunen I think it's ok now

**Comment by surma** [comment]
Great work, @ahlechandre!

I will close this issue, as the original issue is the actual feature request. We will link to this if necessary.

**Comment by brianthelion** [comment]
@tleunen Any chance there's a path for this to enter react-mdl?

**Comment by tleunen** [comment]
@brianhall Not really, unless it's implemented in MDL first.
