### ISSUE TITLE
[1.0.3] Distribution Commit Build Fail

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#1422]
Trying to build from commit: 9bfbb76e57fa598ced9117e53b65b06028eeb920 throws:

Error: Cannot find module './utils/uniffe.js'

as gulpfile.js:27:14 is requiring this file not included in the branch.

**Comment by Zodiase** [comment]
Or am I not supposed to build from the release branch?

**Comment by tleunen** [comment]
I think the release branch is just there to deliver files, not for building stuff

**Comment by Zodiase** [comment]
@tleunen
Then there's this confusion about which branch should I be monitoring for updating my apps/packages which use custom builds of MDL.
Also, if this is not for building, then why include the src files and the gulpfile, right?

But things in this branch are "official", so I think I should watch this branch, but I can't build from this branch, so when I see a new commit in this branch, I go to the master and pull from there?

**Comment by surma** [comment]
@Zodiase @tleunen Release branch is supposed to be able to produce a build with the provided gulp file. We just missed to add the new files introduced in #1365 to that branch. We’ll fix that in 1.0.4 that will hopefully be released in the next few days.

**Comment by tleunen** [comment]
One more reason to simplify all this :D
